ASFLAGS_ADDITIONAL = -mcpu=cortex-m4 -mthumb -mlittle-endian -mthumb-interwork -mfpu=fpv4-sp-d16 $(MW_FLOATING_POINT_ABI_ARGS)
TARGET_LOAD_CMD = 
TARGET_LOAD_CMD_ARGS = 
TARGET_PKG_INSTALLDIR = D:/MATLAB/R2026a/toolbox/stm32b/STM32T~1/STM32G~1
STACK_SIZE = 512
